# Security
- type: entity
  name: security loot spawner
  suffix: Gear, Simple
  id: LootSpawnerSecurityBasic
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Objects/Weapons/Melee/flash.rsi
          state: flash
    - type: GenericSpawner
      entityTable: BasicLootSecurityEntityTable

- type: entity
  name: security loot spawner
  suffix: Gear, Better
  id: LootSpawnerSecurity
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Objects/Weapons/Melee/flash.rsi
          state: flash
    - type: GenericSpawner
      entityTable: LootSecurityEntityTable

# Armory loot spawner
# Automatics are a complete mess right now, so the AK-MS And WT-550 have been commented out for consistency's sake. I have no idea what role these guns are supposed to fufill.
- type: entity
  name: armory loot spawner
  suffix: Guns, Armor
  id: LootSpawnerArmory
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Clothing/OuterClothing/Armor/security.rsi
          state: icon
        - sprite: Objects/Weapons/Guns/Shotguns/pump.rsi
          state: icon
    - type: GenericSpawner
      entityTable: LootArmoryEntityTable
      offset: 0.0

- type: entity
  name: armory loot spawner
  suffix: Guns
  id: LootSpawnerArmoryGunsOnly
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Objects/Weapons/Guns/Shotguns/pump.rsi
          state: icon
    - type: GenericSpawner
      entityTable: LootArmoryGunsEntityTable
      offset: 0.0

- type: entity
  name: armory loot spawner
  suffix: Armor
  id: LootSpawnerArmoryArmorOnly
  parent: MarkerBase
  components:
    - type: Sprite
      layers:
        - state: red
        - sprite: Clothing/OuterClothing/Armor/security.rsi
          state: icon
    - type: GenericSpawner
      entityTable: LootArmoryArmorEntityTable
      offset: 0.0
